### ISSUE TITLE
support for comments?

### ISSUE THREAD

**Issue by mavenraven** [mhshams/dahgan#28]
Hey there! I'm trying to find a YAML 1.2 parser that supports preserving comments for the JVM. Right now, the only parser that I've found that supports them is http://yaml.readthedocs.io/en/latest/pyyaml.html . Any chance that dahgan will in the future?

@kareez

**Comment by kareez** [comment]
Not sure if I understood you correctly. Dahgan is only a yaml parser and can be used for unmarshalling only. It supports the 1.2 spec fully, including the comments.

**Comment by mavenraven** [comment]
What I mean is that when I tried to unmarshal via `io.dahgan.loader.LoaderKt.load(file)`, the resulting data structure doesn't contain the comments in the file. So, if I were to dump the data structure back to disk, I'd lose the comments.

Basically, my use case is that I want to programmatically modify a yaml file that contains comments, without losing the comments.

**Comment by mavenraven** [comment]
To put it another way, I'd like to behavior here

https://github.com/kareez/dahgan/blob/060a19ee63e1943a5349536590bd18bd2a3cc894/loader/src/main/kotlin/io/dahgan/loader/Loader.kt#L67-L68

to be configurable to not ignore.

**Comment by kareez** [comment]
@mavenraven, I see your point now. I can update the loader to keep the comments, most probably after new year vacations. But you will need another library to dump the data, at least for the time being

**Comment by mavenraven** [comment]
cool, thanks @kareez !

**Comment by kareez** [comment]
Seems comments are not  associated with any node in yaml. This makes it very difficult to preserve them during load. 

[ Comments](https://yaml.org/spec/1.2/spec.html#id2767100)
